import 'package:get/get.dart';

class MyLocal implements Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    "ar" : {
      "Login" : "تسجيل الدخول" ,
      "Log in" : "تسجيل الدخول" ,
      'Your Phone' : 'هاتفك' ,
      'Password' : 'كلمة المرور' ,
      'Your Password' : 'كلمة المرور الخاصة بك' ,
      'Enter Verification Code' : 'أدخل رمز التحقق' ,
      'You Receive SMS have Code' : 'تتلقى الرسائل القصيرة لديك رمز' ,
      'OTP' : 'كود التحقق',
      'Fingerprint and Face ID' : 'بصمة الإصبع ومعرف الوجه',
      'Verify' : 'تأكيد',
      'Good Morning, Joly' : 'صباح الخير , جولي',
      'Your Children' : 'أطفالك',
      'Arrive to you' : 'سيصل إليك',
      'Track Bus' : 'مسار الأتوبيس',
      'Class: ' : 'فصل ',
      'Shady Ayman' : 'شادي أيمن',
      'Manar Ali' : 'منار علي',
      'Today’s Bus : ' : 'أتوبيس اليوم : ' ,
      'Available Today' : 'متاح اليوم' ,
      'Delay 10 Mins' : 'تأخير 10 دقائق' ,
      'Take Bus' : 'هركب الأتوبيس' ,
      'Aya Essam' : 'أية عصام' ,
      'Call' : 'اتصال' ,
      'Chat' : 'محادثة' ,
      'Advanced' : 'متقدم' ,
      'chat' : 'المحادثة' ,
      'Bus : 1458 ى ر س' : 'أتوبيس : 1458 ى ر س' ,
      'Atten..' : 'الغياب' ,
      'Track' : 'المسار' ,
      'Arrive to you.' : 'سيصل اليك' ,
      '25 Min' : '25 دقيقة' ,
      '25 Min.' : '25 دقيقة.' ,
      'Home' : 'الرئيسية' ,
      '.' : '.' ,
      'Absent' : 'غائب' ,
      'Set Reminder' : 'تعيين تذكير' ,
      'You Set Reminder Before Bus Arrive' : 'قمت بتعيين تذكير قبل وصول الأتوبيس' ,
      'Holiday' : 'اجازة' ,
      'Add Absent Days' : 'إضافة أيام الغياب' ,
      'Attendance' : 'الغياب' ,
      'Online' : 'متصل' ,
      'Type here...' : 'أكتب هنا...' ,
      'FAQ' : 'تعليمات' ,
      'Children Data' : 'بيانات الأطفال' ,
      'Today' : 'اليوم' ,
      'Yesterday' : 'أمس' ,
      'Driver Name ' : 'اسم السائق' ,
      'Ahmed Emad' : 'احمد عماد' ,
      'Bus Number' : 'رقم الأتوبيس' ,
      'Okay' : 'موافق' ,
      'Father Name' : 'اسم الأب' ,
      'Ayman Fayez Mansor' : 'ايمن فايز منصور' ,
      'Male' : 'ذكر' ,
      'Year' : 'السنة' ,
      'Contact No.' : 'رقم التواصل.' ,
      'Date of Birth' : 'تاريخ الميلاد' ,
      'The bus has\nfinally arrived!' : 'وصل الأتوبيس\nأخيرًا!' ,
      'Notifications' : 'الإشعارات' ,
      'Arrival Reminder' : 'تذكير بالوصول' ,
      '07:35 AM' : '07:35 ص' ,
      'Taken From School' : 'مأخوذة من المدرسة' ,
      '03:35 PM' : '03:35 م' ,
      '02:45 PM' : '02:45 م' ,
      'Minutes' : 'دقائق' ,
      'Cancel' : 'الغاء' ,
      'Set' : 'تعيين' ,
      'General' : 'عام' ,
      'Language' : 'اللغة' ,
      "Due to Accident Near El Namas St. July's Bus is delayed by 20 mins, Don't worry every one is safes" : 'بسبب حادث بالقرب من شارع النماص، أتوبيس جولي تأخر 20 دقيقة، متقلقش كل واحد في أمان' ,
      'Alarm' : 'تنبيه' ,
      'Tracking Bus' : 'مسارات الأتوبيس' ,
      'Tracking' : 'المسار' ,
      'Save' : 'حفظ' ,
      'Logout' : 'تسجيل الخروج' ,
      'Settings' : 'الإعدادات' ,
      'Log out' : 'تسجيل الخروج' ,
      'Are You Sure Logout?' : 'هل أنت متأكد من تسجيل الخروج؟'  ,
      'Bus Info' : 'الباص' ,
      'arrived : 7:45 AM' : 'الوصول:  45: 7 ص' ,
      'Select Absent Day' : 'اختر يوم الغياب' ,
      'Joly’s Bus has left from school, it will reach location in 35 mins' : 'غادر أتوبيس جولي من المدرسة، وسوف تصل إلى الموقع في 35 دقيقة' ,
      'Joly’s Bus about to reach you location in 20 mins' : 'أتوبيس جولي على وشك الوصول إلى موقعك خلال 20 دقيقة' ,
      'What is the School Bus App?' : 'ما هو تطبيق School Bus؟' ,
      'How can I download the School Bus App?' : 'كيف يمكنني تنزيل تطبيق School Bus؟' ,
      'What information does the app provide?' : 'ما هي المعلومات التي يوفرها التطبيق؟' ,
      'How does the app work?' : 'كيف يعمل التطبيق؟' ,
      'Is the app free to use?' : 'هل التطبيق مجاني للاستخدام؟' ,
      'How accurate are the estimated arrival times?' : 'ما مدى دقة الأوقات المقدرة للوصول؟' ,
      "Is the app secure? How is my child's information protected?" : 'هل التطبيق آمن؟ كيف تتم حماية معلومات طفلي؟' ,
      "We prioritize the security of your child's information. The app typically uses secure login methods, and personal data is encrypted to protect privacy."
          : 'نحن نعطي الأولوية لأمن معلومات طفلك. يستخدم التطبيق عادةً طرق تسجيل دخول آمنة، ويتم تشفير البيانات الشخصية لحماية الخصوصية.' ,
      'Can I receive notifications for delays or changes?' : 'هل يمكنني تلقي إشعارات بشأن التأخير أو التغييرات؟' ,
      "Yes, the app can send push notifications to alert you about delays, route changes, or other important updates related to your child's school bus."
          : 'نعم، يمكن للتطبيق إرسال إشعارات لتنبيهك بشأن التأخير أو تغييرات المسار أو التحديثات المهمة الأخرى المتعلقة بالأتوبيسات المدرسية لطفلك؟' ,
      'The estimated arrival times are based on real-time GPS data and traffic conditions. They are generally accurate, but factors like traffic jams or weather conditions might occasionally cause deviations.'
          : 'تعتمد أوقات الوصول المقدرة على بيانات (GPS) وظروف حركة المرور في الوقت الفعلي. وهي دقيقة بشكل عام، ولكن عوامل مثل زحمة المرور أو الظروف الجوية قد تسبب انحرافات في بعض الأحيان.' ,
      "How do I set up the app for my child's school?" : "كيف أقوم بإعداد التطبيق لمدرسة طفلي؟" ,
      "You can typically select your child's school within the app and add your child to the system using their student ID. This will allow you to receive accurate information about their bus route and schedule."
          : 'يمكنك عادةً تحديد مدرسة طفلك داخل التطبيق وإضافة طفلك إلى النظام باستخدام كارنية الطالب. سيسمح لك ذلك بتلقي معلومات دقيقة حول مسار الحافلة وجدولها الزمني.' ,
      'The app is generally free to download and use, but some advanced features may require a subscription or in-app purchase.'
          : 'التطبيق مجاني بشكل عام للتنزيل والاستخدام، ولكن قد تتطلب بعض الميزات المتقدمة اشتراكًا أو شراء داخل التطبيق.' ,
      'The app uses GPS technology to track the location of school buses. When parents or students log in, they can see the real-time location of their bus, its route, and any delays.'
          : 'يستخدم التطبيق تقنية GPS لتتبع موقع الأتوبيسات المدرسية. عندما يقوم أولياء الأمور أو الطلاب بتسجيل الدخول، يمكنهم رؤية الموقع الفعلي للأتوبيسات ومسارها وأي تأخيرات.' ,
      'The app provides real-time updates on school bus locations, estimated arrival times, route changes, delays, and safety notifications. It helps parents and students stay informed about bus movements.'
          : 'يوفر التطبيق تحديثات في الوقت الفعلي عن مواقع الأتوبيسات المدرسية، وأوقات الوصول المقدرة، وتغييرات المسار، والتأخير، وإشعارات السلامة. يساعد أولياء الأمور والطلاب على البقاء على اطلاع بحركات الأتوبيسات.؟' ,
      'You can download the School Bus App from the Apple App Store or Google Play Store. Simply search for \"School Bus App\" and look for our official logo.'
          : 'يمكنك تنزيل تطبيق School Bus من Apple App Store أو Google Play Store. ما عليك سوى البحث عن \"School Bus App\" وابحث عن شعارنا الرسمي.' ,
      'The School Bus App is a mobile application designed to provide parents, students, and schools with real-time information about school bus routes, schedules, and safety updates.'
          : 'تطبيق School Bus هو تطبيق جوال مصمم لتزويد أولياء الأمور والطلاب والمدارس بمعلومات في الوقت الفعلي حول مسارات الأتوبيسات المدرسية وجداولها الزمنية وتحديثات السلامة.' ,

      "Create Account" : "إنشاء حساب" ,
      "Sign up":"إنشاء حساب",
      "School account":"المدرسه",
      "Parents":"الوالد",
      "Don't Have an account yet?":" ليس لديك حساب؟",
      "Sign Up":"إنشاء حساب",
      "Already Have an account?":"لديك حساب؟  ",
      "Sign in":"تسجيل دخول",
      "Phone Number *":"رقم التليفون *",
      'Please enter your phone number':"الرجاء إدخال رقم التليفون",
      "Please enter your name":"الرجاء إدخال الإسم",
      "Didn't receive the OTP":"لم أتلقى كود التحقق ",
      "Resend OTP?":"إعادة إرسال كود التحقق؟",
      "School logo":"لوجو المدرسة",
      "School name in English":"أسم المدرسة بالإنجليزى",
      "School name in Arabic":"أسم المدرسة بالعربى",
      "Address":"العنوان",
      "Coordinator Name":"أسم المنسق",
      "Support Number":"رقم الدعم",
      "Your Name":"الأسم",
      "Submit":"حفظ",
      "Welcome":"مرحباً",
      "Supervisors":"المشرفين",
      "Buses":"الاتوبيسات",
      "Notification":"الاشعارات",
      "Supervisor":"المشرف",
      "Search Name":"البحث بالاسم",
      "1 s":"1 ث",
      "Email":"إيميل",
      "Resend invitation":"إرسال دعوه",
      "Salam Language School":"مدرسة السلام اللغات",
      "Driver Number":"رقم السائق",
      "Your Number":"رقمك",
      "Bus Photos":"صور الاتوبيس",
      "Add":"إضافة",
      "Driver photo":"صورة السائق",
      "*":"*",
      "Send invitation":"إرسال دعوة",
      'You haven’t received any \n invitation. \n' : 'لم تتلقي أي دعوة.\n',
      'suggest you to get in touch \nwith your school. \n' : 'أقترح عليك التواصل مع مدرستك.',
      "Nearest to you" : "الأقرب إليك" ,
      "Skip" : "تخطي" ,
      "Show all" : "عرض الكل" ,
      "Parents" : "الوالدين" ,
      "Your Bus" : "الحافلة الخاصة بك" ,
      "Name" : "الأسم" ,
      "Please enter your invitation phone number" : "الرجاء إدخال رقم هاتف الدعوة الخاص بك" ,
      "Welcome, " : "مرحبا, " ,
      "My Bus" : "حافلتي" ,
      "No Data Found" : "لا توجد بيانات" ,
      "No Assigned dates Found" : "لم يتم العثور علي التواريخ المخصصه" ,
      "No Notification Found" : "لا توجد إشعارات" ,
      "You haven’t added any \n data yet" : 'لم تقم بإضافة أي شئ من البيانات حتي الأن',
      "You haven’t added any \n dates yet" : 'لم تقم بإضافة أي شئ من التواريخ حتي الأن',
      "You haven’t added any \n children yet" : 'لم تقم بإضافة أي من الأطفال حتي الأن',
      "You haven’t added any \n buses yet" : 'لم تقم بإضافة أي من الحافلات حتي الأن',
      "You haven’t added any \n supervisors yet" : 'لم تقم بإضافة أي من المشرفين حتي الأن',
      "You haven’t received any \nnotification yet" : 'لم تتلقي أي إشعار حتي الأن',
      "Schools worked for" : "عملت المدارس ل" ,
      "Name *" : "الأسم *" ,
      'User' : "المستخم" ,
      'Buses' : "الحافلات" ,
      'Already Have an account?' : "يوجد حساب؟" ,
      'School' : "المدرسة" ,
      'Supervisor' : "المشرف" ,
      'Number' : "رقم التليفون" ,
      'Number: ' : "رقم التليفون: " ,
      'Parent' : "الوالدين" ,
      "Join as" : "انضم ك" ,
      " Sign Up" : " انشاء حساب" ,
      " Sign in" : " تسجيل الدخول" ,
      "Don’t have an account yet?" : "لا يوجد حساب؟" ,
      "Log in" : "تسجيل الدخول" ,
      'Phone Number' : 'رقم التليفون' ,
      'Phone Number*' : 'رقم التليفون*' ,
      'Your Phone' : 'هاتفك' ,
      'Password' : 'كلمة المرور' ,
      'Your Password' : 'كلمة المرور الخاصة بك' ,
      'Enter Verification Code' : 'أدخل رمز التحقق' ,
      'You Receive SMS have Code' : 'سوف تتلقى رسالة نصية تحتوي على الرمز' ,
      'Didn’t receive the OTP' : 'لم اتلقي كود التحقق' ,
      '  Resend OTP ? ' : ' إعادة ارسال كود التحقق' ,
      'OTP' : 'كود التحقق',
      'Fingerprint and Face ID' : 'بصمة الإصبع ومعرف الوجه',
      'Verify' : 'تأكيد',
      'Your Children' : 'أطفالك',
      'Arrive to you' : 'سيصل إليك',
      'Track Bus' : 'مسار الحافلة',
      'Class: ' : 'فصل ',
      'Today’s Bus : ' : 'أتوبيس اليوم : ' ,
      'Available Today' : 'متاح اليوم' ,
      'Delay 10 Mins' : 'تأخير 10 دقائق' ,
      'Take Bus' : ' استقل حافلة' ,
      'Call' : 'اتصال' ,
      'Delete Account' : 'حذف الحساب' ,
      'Chat' : 'محادثة' ,
      'Calendar' : 'التقويم' ,
      'Advanced' : 'متقدم' ,
      'chat' : 'المحادثة' ,
      'Bus : 1458 ى ر س' : 'أتوبيس : 1458 ى ر س' ,
      'Atten..' : 'الحضور' ,
      'Track' : 'المسار' ,
      'Arrive to you.' : 'سيصل اليك' ,
      '’s bus' : ' أتوبيس' ,
      'Min' : 'دقيقة' ,
      'Home' : 'الرئيسية' ,
      'Absent' : 'غائب' ,
      'Remove' : 'حذف' ,
      'Set Reminder' : ' تذكير' ,
      'Set home location' : ' ضبط موقع المنزل' ,
      'Go to home page' : 'اذهب إلى الصفحة الرئيسية' ,
      'Invitation sent successfully' : 'تم إرسال الدعوة بنجاح' ,
      'Data saved successfully' : 'تم حفظ المعلومات بنجاح' ,
      'Parent deleted successfully' : 'تم حذف الوالد بنجاح' ,
      'Child removed successfully' : 'تم حذف الطفل بنجاح' ,
      'You Set Reminder Before Bus Arrive' : 'قمت بتعيين تذكير قبل وصول الأتوبيس' ,
      'Holiday' : 'اجازة' ,
      'Add Absent Days' : 'إضافة أيام الغياب' ,
      'Attendance' : 'الحضور' ,
      'Attendances' : 'الحضور' ,
      'End Your trip' : 'انهي رحلتك' ,
      'Start your trip' : 'ابدأ رحلتك' ,
      'Online' : 'متصل' ,
      'Type here...' : 'أكتب هنا...' ,
      'FAQ' : 'تعليمات' ,
      'Children Data' : 'بيانات الأطفال' ,
      'Today' : 'اليوم' ,
      'Yesterday' : 'أمس' ,
      'Check out' : 'تسجيل الخروج' ,
      'Check in' : 'تسجيل الدخول' ,
      'Driver Name' : 'اسم السائق' ,
      'Second Supervisor' : 'المشرف الثاني' ,
      'Driver Number' : 'رقم السائق' ,
      'Driver photo' : 'صورة السائق' ,
      'Bus Number' : 'رقم الحافلة' ,
      'Bus photos' : 'صور الحافلة' ,
      'Bus Photos' : 'صور الحافلة' ,
      'Okay' : 'موافق' ,
      'Father Name' : 'اسم الأب' ,
      'Father' : 'الأب' ,
      'Number of children' : 'عدد الأطفال' ,
      'Gender' : 'النوع' ,
      'Send invitation' : 'إرسال دعوة',
      'Male' : 'ذكر' ,
      'My Children' : 'أطفالي' ,
      'Year' : 'السنة' ,
      'Edit' : 'تعديل' ,
      'Child' : 'الطفل' ,
      'Supervisor : ' : 'مشرف : ' ,
      '1s' : '1 ث' ,
      'Contact No.' : 'رقم التواصل.' ,
      'Date of Birth' : 'تاريخ الميلاد' ,
      'The bus has\nfinally arrived!' : 'أخيرا ! \n وصلت الحافلة' ,
      'Notifications' : 'الإشعارات' ,
      'Arrival Reminder' : 'تذكير بالوصول' ,
      'AM' : 'ص' ,
      'Taken From School' : '	تم التحرك من المدرسه' ,
      'PM' : 'م' ,
      'Minutes' : 'دقائق' ,
      'Cancel' : 'الغاء' ,
      'Delete' : 'حذف' ,
      'Set' : 'تعيين' ,
      'Children' : 'الأطفال' ,
      'Decline' : 'رفض' ,
      'Declined' : 'تم الرفض' ,
      'Accept' : 'قبول' ,
      'Accepted' : 'تم القبول' ,
      'Holidays' :'العطلات',
      'Fixed weekend' : 'عطلة نهاية الأسبوع الثابتة' ,
      'General' : 'عام' ,
      'weekend' : 'عطلة نهاية الاسبوع' ,
      'Students' : 'الطلاب' ,
      'Student' : 'الطالب' ,
      'Filter' : 'التصفية' ,
      'Added yesterday' : 'تمت إضافته بالأمس' ,
      'Waiting' : 'المنتظرين' ,
      'Apply' : 'موافق' ,
      'Reset' : 'اعادة ضبط' ,
      'Search Name' : 'اسم البحث' ,
      'Email' : 'الايميل' ,
      'Joined yesterday' : 'انضم أمس' ,
      'Change profile picture' : 'تغيير الصورة الشخصية' ,
      'Select profile picture' : 'تحديد الصورة الشخصية' ,
      'Edit Profile' : 'تعديل الصفحة الشخصية' ,
      'Grade': 'الصف',
      'Grade: ': 'الصف: ',
      'Address: ': 'العنوان: ',
      'Female': 'انثي',
      'Add': 'إضافة',
      'Min.' : 'دقيقة.' ,
      'bus Tracking': 'مسار الحافلة',
      'Delays': 'التأخير',
      'Cancel Absence': 'إلغاء الغياب',
      'Number *': 'رقم التليفون *',
      'Home':'الرئسيه',
      'Vacations':'الاجازات',

      'Add Additional Data': 'إضافة بيانات إضافية',
      'Location *': 'العنوان',
      'Location' : 'العنوان',
      'Additional Data': 'بيانات إضافية',
      'Profile' : 'الصفحة الشخصية' ,
      'locate me' : 'تحديد موقعك' ,
      'Language' : 'اللغة' ,
      "Due to Accident Near El Namas St. July's Bus is delayed by 20 mins, Don't worry every one is safes" : 'بسبب حادث بالقرب من شارع النماص، حافلة جولي تأخرت 20 دقيقة، لا تقلق الجميع بامان' ,
      'Alarm' : 'تنبيه' ,
      'Tracking Bus' : 'مسار الحافلة' ,
      'Tracking' : 'المسار' ,
      ' Tracking' : ' مسار' ,
      'Save' : 'حفظ' ,
      'Logout' : 'تسجيل الخروج' ,
      'Settings' : 'الإعدادات' ,
      'Log out' : 'تسجيل الخروج' ,
      'log out' : 'تسجيل الخروج' ,
      'Are You Sure Logout?' : 'هل أنت متأكد من تسجيل الخروج؟'  ,
      'Bus Info' : 'الحافلة' ,
      'arrived : 7:45 AM' : 'وصل:  45: 7 ص' ,
      'You have declined \n' : 'لقد رفضت  \n',
      'or cancelled your invitation. \n'
          'If this was unintentional,\n'
          'please contact your school \n'
          'to request another invitation \n'
          'to use the application' :
      ' او ألغيت دعوتك. إذا \n'
          'كان هذا غير مقصود،\n'
          'الرجاء الاتصال بمدرستك \n'
          'لطلب دعوة أخرى \n'
          'لاستخدام التطبيق',
      'Select Absent Day' : 'اختر يوم الغياب' ,
      'Are you sure you want to \n '
          'remove this child ?' : 'هل أنت متأكد أنك تريد \n حذف هذا الطفل؟',
      'Are You Sure you want to \n'
          'delete account ?' : 'هل أنت متأكد أنك تريد \n حذف الحساب؟',
      'Are you sure you want to \n '
          'decline invitation ?' : 'هل أنت متأكد أنك تريد \n رفض الدعوة؟',
      'Are You Sure you want to \n'
          'delete this parent ?' : 'هل أنت متأكد أنك تريد \n حذف هذا الوالد؟',
      'You have an invitation \n': 'لديك دعوة \n' ,
      'from El Salam School to \n '
          'join the application as a bus \n '
          'supervisor for your school' : 'من مدرسة السلام للانضمام إلى \n التطبيق ك مشرف الحافلة لمدرستك',
      'from El Salam School to \n '
          'join the application as a \n '
          'Parent for your child Mariam' : ' من مدرسة السلام \n للانضمام إلى التطبيق ك والد\n لطفلك مريم' ,
      'Joly’s Bus has left from school, it will reach location in 35 mins' : 'غادرت حافلة جولي من المدرسة، وسوف تصل إلى الموقع في 35 دقيقة' ,
      'Joly’s Bus about to reach you location in 20 mins' : 'حافلة جولي على وشك الوصول إلى موقعك خلال 20 دقيقة' ,
      'What is the School Bus App?' : 'ما هو تطبيق School Bus؟' ,
      'How can I download the School Bus App?' : 'كيف يمكنني تنزيل تطبيق School Bus؟' ,
      'What information does the app provide?' : 'ما هي المعلومات التي يوفرها التطبيق؟' ,
      'How does the app work?' : 'كيف يعمل التطبيق؟' ,
      'Is the app free to use?' : 'هل التطبيق مجاني للاستخدام؟' ,
      'How accurate are the estimated arrival times?' : 'ما مدى دقة الأوقات المقدرة للوصول؟' ,
      "Is the app secure? How is my child's information protected?" : 'هل التطبيق آمن؟ كيف تتم حماية معلومات طفلي؟' ,
      "We prioritize the security of your child's information. The app typically uses secure login methods, and personal data is encrypted to protect privacy."
          : 'نحن نعطي الأولوية لأمن معلومات طفلك. يستخدم التطبيق عادةً طرق تسجيل دخول آمنة، ويتم تشفير البيانات الشخصية لحماية الخصوصية.' ,
      'Can I receive notifications for delays or changes?' : 'هل يمكنني تلقي إشعارات بشأن التأخير أو التغييرات؟' ,
      "Yes, the app can send push notifications to alert you about delays, route changes, or other important updates related to your child's school bus."
          : 'نعم، يمكن للتطبيق إرسال إشعارات لتنبيهك بشأن التأخير أو تغييرات المسار أو التحديثات المهمة الأخرى المتعلقة بالأتوبيسات المدرسية لطفلك؟' ,
      'The estimated arrival times are based on real-time GPS data and traffic conditions. They are generally accurate, but factors like traffic jams or weather conditions might occasionally cause deviations.'
          : 'تعتمد أوقات الوصول المقدرة على بيانات (GPS) وظروف حركة المرور في الوقت الفعلي. وهي دقيقة بشكل عام، ولكن عوامل مثل زحمة المرور أو الظروف الجوية قد تسبب انحرافات في بعض الأحيان.' ,
      "How do I set up the app for my child's school?" : "كيف أقوم بإعداد التطبيق لمدرسة طفلي؟" ,
      "You can typically select your child's school within the app and add your child to the system using their student ID. This will allow you to receive accurate information about their bus route and schedule."
          : 'يمكنك عادةً تحديد مدرسة طفلك داخل التطبيق وإضافة طفلك إلى النظام باستخدام كارنية الطالب. سيسمح لك ذلك بتلقي معلومات دقيقة حول مسار الحافلة وجدولها الزمني.' ,
      'The app is generally free to download and use, but some advanced features may require a subscription or in-app purchase.'
          : 'التطبيق مجاني بشكل عام للتنزيل والاستخدام، ولكن قد تتطلب بعض الميزات المتقدمة اشتراكًا أو شراء داخل التطبيق.' ,
      'The app uses GPS technology to track the location of school buses. When parents or students log in, they can see the real-time location of their bus, its route, and any delays.'
          : 'يستخدم التطبيق تقنية GPS لتتبع موقع الأتوبيسات المدرسية. عندما يقوم أولياء الأمور أو الطلاب بتسجيل الدخول، يمكنهم رؤية الموقع الفعلي للأتوبيسات ومسارها وأي تأخيرات.' ,
      'The app provides real-time updates on school bus locations, estimated arrival times, route changes, delays, and safety notifications. It helps parents and students stay informed about bus movements.'
          : 'يوفر التطبيق تحديثات في الوقت الفعلي عن مواقع الأتوبيسات المدرسية، وأوقات الوصول المقدرة، وتغييرات المسار، والتأخير، وإشعارات السلامة. يساعد أولياء الأمور والطلاب على البقاء على اطلاع بحركات الأتوبيسات.؟' ,
      'You can download the School Bus App from the Apple App Store or Google Play Store. Simply search for \"School Bus App\" and look for our official logo.'
          : 'يمكنك تنزيل تطبيق School Bus من Apple App Store أو Google Play Store. ما عليك سوى البحث عن \"School Bus App\" وابحث عن شعارنا الرسمي.' ,
      'The School Bus App is a mobile application designed to provide parents, students, and schools with real-time information about school bus routes, schedules, and safety updates.'
          : 'تطبيق School Bus هو تطبيق جوال مصمم لتزويد أولياء الأمور والطلاب والمدارس بمعلومات في الوقت الفعلي حول مسارات الأتوبيسات المدرسية وجداولها الزمنية وتحديثات السلامة.' ,








    } ,






    "en" : {
      "Login" : "Login" ,
      "Log in" : "Log in" ,
      'Phone Number' : 'Phone Number' ,
      'Your Phone' : 'Your Phone' ,
      'Password' : 'Password' ,
      'Your Password' : 'Your Password' ,
      'Enter Verification Code' : 'Enter Verification Code' ,
      'You Receive SMS have Code' : 'You Receive SMS have Code' ,
      'OTP' : 'OTP' ,
      'Fingerprint and Face ID' : 'Fingerprint and Face ID' ,
      'Okay' : 'Okay' ,
      'Bus Number' : 'Bus Number' ,
      'Alarm' : 'Alarm' ,
      'General' : 'General' ,
      'Verify' : 'Verify' ,
      'Ahmed Emad' : 'Ahmed Emad' ,
      'Good Morning, Joly' : 'Good Morning, Joly' ,
      'Your Children' : 'Your Children' ,
      'Supervisor' : 'Supervisor' ,
      '.' : '.' ,
      '25 Min' : '25 Min' ,
      'Arrive to you' : 'Arrive to you' ,
      'Track Bus' : 'Track Bus' ,
      'Class: ' : 'Class: ' ,
      'Shady Ayman' : 'Shady Ayman' ,
      'Today’s Bus : ' : 'Today’s Bus :' ,
      'Available Today' : 'Available Today' ,
      'Delay 10 Mins' : 'Delay 10 Mins' ,
      'Take Bus' : 'Take Bus' ,
      'Aya Essam' : 'Aya Essam' ,
      'Call' : 'Call' ,
      'Gender' : 'Gender' ,
      'Male' : 'Male' ,
      'Year' : 'Year' ,
      'Contact No.' : 'Contact No.' ,
      'Date of Birth' : 'Date of Birth' ,
      'Ayman Fayez Mansor' : 'Ayman Fayez Mansor' ,
      'Father Name' : 'Father Name' ,
      'Children Data' : 'Children Data' ,
      'Minutes' : 'Minutes' ,
      'Chat' : 'Chat' ,
      'Profile' : 'Profile' ,
      'Arrive to you.' : 'Arrive to you.' ,
      '25 Min.' : '25 Min.' ,
      'You Set Reminder Before Bus Arrive' : 'You Set Reminder Before Bus Arrive' ,
      'chat' : 'Chat' ,
      'Manar Ali' : 'Manar Ali' ,
      'arrived : 7:45 AM' : 'arrived : 7:45 AM' ,
      'Bus : 1458 ى ر س' : 'Bus : 1458 ى ر س' ,
      'Atten..' : 'Atten..' ,
      'Track' : 'Track' ,
      'Absent' : 'Absent' ,
      'Holiday' : 'Holiday' ,
      'Add Absent Days' : 'Add Absent Days' ,
      'Attendance' : 'Attendance' ,
      'Online' : 'Online' ,
      'The bus has\nfinally arrived!' : 'The bus has\nfinally arrived!' ,
      'Cancel' : 'Cancel' ,
      'Type here...' : 'Type here...' ,
      'Are You Sure Logout?' : 'Are You Sure Logout?' ,
      'FAQ' : 'FAQ' ,
      'Language' : 'Language' ,
      'Settings' : 'Settings' ,
      'Advanced' : 'Advanced' ,
      'Save' : 'Save' ,
      'Yesterday' : 'Yesterday' ,
      'Today' : 'Today' ,
      'Set' : 'Set' ,
      'Logout' : 'Logout' ,
      'Log out' : 'Log out' ,
      'Notifications' : 'Notifications' ,
      'Arrival Reminder' : 'Arrival Reminder' ,
      '07:35 AM' : '07:35 AM' ,
      '03:35 PM' : '03:35 PM' ,
      '02:45 PM' : '02:45 PM' ,
      "Due to Accident Near El Namas St. July's Bus is delayed by 20 mins, Don't worry every one is safes"
          : "Due to Accident Near El Namas St. July's Bus is delayed by 20 mins, Don't worry every one is safes" ,
      'Alarm' : 'Alarm' ,
      'Tracking Bus' : 'Tracking Bus' ,
      'Tracking' : 'Tracking' ,
      'Bus Info' : 'Bus Info' ,
      'Set Reminder' : 'Set Reminder' ,
      'Select Absent Day' : 'Select Absent Day' ,
      'Taken From School' : 'Taken From School' ,
      'Joly’s Bus has left from school, it will reach location in 35 mins' : 'Joly’s Bus has left from school, it will reach location in 35 mins' ,
      'Joly’s Bus about to reach you location in 20 mins' : 'Joly’s Bus about to reach you location in 20 mins' ,
      'What is the School Bus App?' : 'What is the School Bus App?' ,
      'How can I download the School Bus App?' : 'How can I download the School Bus App?' ,
      'What information does the app provide?' : 'What information does the app provide?' ,
      'How does the app work?' : 'How does the app work?' ,
      'Is the app free to use?' : 'Is the app free to use?' ,
      'How accurate are the estimated arrival times?' : 'How accurate are the estimated arrival times?' ,
      'Can I receive notifications for delays or changes?' : 'Can I receive notifications for delays or changes?' ,
      "Is the app secure? How is my child's information protected?" : "Is the app secure? How is my child's information protected?" ,
      "We prioritize the security of your child's information. The app typically uses secure login methods, and personal data is encrypted to protect privacy."
          : "We prioritize the security of your child's information. The app typically uses secure login methods, and personal data is encrypted to protect privacy." ,
      "Yes, the app can send push notifications to alert you about delays, route changes, or other important updates related to your child's school bus"
          : "Yes, the app can send push notifications to alert you about delays, route changes, or other important updates related to your child's school bus" ,
      'The estimated arrival times are based on real-time GPS data and traffic conditions. They are generally accurate, but factors like traffic jams or weather conditions might occasionally cause deviations.'
          : 'The estimated arrival times are based on real-time GPS data and traffic conditions. They are generally accurate, but factors like traffic jams or weather conditions might occasionally cause deviations.' ,
      "How do I set up the app for my child's school?" : "How do I set up the app for my child's school?" ,
      "You can typically select your child's school within the app and add your child to the system using their student ID. This will allow you to receive accurate information about their bus route and schedule."
          : "You can typically select your child's school within the app and add your child to the system using their student ID. This will allow you to receive accurate information about their bus route and schedule." ,
      'The app is generally free to download and use, but some advanced features may require a subscription or in-app purchase.'
          : 'The app is generally free to download and use, but some advanced features may require a subscription or in-app purchase.' ,
      'The app uses GPS technology to track the location of school buses. When parents or students log in, they can see the real-time location of their bus, its route, and any delays.'
          : 'The app uses GPS technology to track the location of school buses. When parents or students log in, they can see the real-time location of their bus, its route, and any delays.' ,
      'The app provides real-time updates on school bus locations, estimated arrival times, route changes, delays, and safety notifications. It helps parents and students stay informed about bus movements.'
          : 'The app provides real-time updates on school bus locations, estimated arrival times, route changes, delays, and safety notifications. It helps parents and students stay informed about bus movements.' ,
      'You can download the School Bus App from the Apple App Store or Google Play Store. Simply search for \"School Bus App\" and look for our official logo.'
          : 'You can download the School Bus App from the Apple App Store or Google Play Store. Simply search for \"School Bus App\" and look for our official logo.' ,
      'The School Bus App is a mobile application designed to provide parents, students, and schools with real-time information about school bus routes, schedules, and safety updates.'
          : 'The School Bus App is a mobile application designed to provide parents, students, and schools with real-time information about school bus routes, schedules, and safety updates.' ,

      "Create Account" : "Create Account",
      "Sign up":"Sign up",
      "Name *":"Name *",
      "Join as":"Join as",
      "School account":"School account",
      "Supervisor":"Supervisor",
      "Parents":"Parents",
      "Don't Have an account yet? ": "Don't Have an account yet? ",
      "Sign Up":"Sign Up",
      "Already Have an account?": "Already Have an account? ",
      "Sign in":"Sign in",
      'School':'School',
      "Phone Number *":"Phone Number *",
      "Name":"Name",
      'Please enter your phone number':'Please enter your phone number',
      "Please enter your name":"Please enter your name",
      "Didn't receive the OTP":"Didn't receive the OTP ",
      "Resend OTP?":"Resend OTP?",
      "School logo":"School logo",
      "School name in English":"School name in English",
      "School name in Arabic":"School name in Arabic",
      "Address":"Address",
      "Coordinator Name":"Coordinator Name",
      "Support Number":"Support Number",
      "Your Name": "Your Name",
      "Name":"Name",
      "Number":"Number",
      "Submit":"Submit",
      "Welcome": "Welcome",
      "Supervisors":"Supervisors",
      "Buses":"Buses",
      "Search Name":"Search Name",
      "1 s":"1 s",
  "Email":"Email",
      "Resend invitation":"Resend invitation",
      "Salam Language School":"Salam Language School",
      "Driver Number":"Driver Number",
      "Your Number":"Your Number",
      "Bus Photos":"Bus Photos",
      "Add":"Add",
      "Driver photo":"Driver photo",
      "*":"*",
      "Send invitation":"Send invitation",
      "Save":"Save"
    } ,
  };

}